### PR TITLE
What i am doing

### PR DESCRIPTION
**Pull request by NickAnson**
What im working on for the project

unnamed 2
unnamed
unnamed 1

### CODE REVIEW

**Comment by willbkeller** [comment]
Alright looks good!

**Comment by willbkeller** [comment]
this all looks pretty good! the one thing is that on the UML we don't use height for the shocks, except adjustable shocks is ok, so for the rest of the shocks just give it a toString and that'll be good enough.
also i just added this picture because i think you left it out just so we have it. Thanks!

screen shot 2017-03-20 at 8 33 27 am

**Comment by willbkeller** [comment]
Just adding this in again with all the methods so you can double check and make sure you guys got them all.
suspension component diagram - page 1-2

**Comment by willbkeller** [comment]
hey Nick i don't know why there are all these conflicts
with the code? why do you have that extra directory src?
@NickAnson

**Comment by NickAnson** [comment]
Fixed it not to sure why there is still conflicts
@willbkeller

**Pull request merged**
