### PR TITLE
Builders complete and up to date

### PR DESCRIPTION
**Pull request by Brandonhenk**

### CODE REVIEW

**Comment by Brandonhenk** [comment]
i don't think I can fix these conflicts

**Comment by willbkeller** [comment]
I'll look at it. Did he say if we couldn't resolve them not to worry about it? Or what do we do?

**Comment by willbkeller** [comment]
@Brandonhenk

**Comment by Brandonhenk** [comment]
Yeah he said not to worry about it I can't figure out why our interfaces are different either

Sent from my iPhone

On Apr 25, 2017, at 5:32 PM, willbkeller <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll look at it. Did he say if we couldn't resolve them not to worry about it? Or what do we do?

**Comment by willbkeller** [comment]
ok i fixed it I think so I'm gonna merge in.
@Brandonhenk

**Pull request merged**
