### PR TITLE
Working on Economy

### PR DESCRIPTION
**Pull request by Wolfencode3000**
Working on Economy
screen shot 2017-03-20 at 8 33 37 am
screen shot 2017-03-20 at 8 31 18 am
screen shot 2017-03-20 at 8 32 27 am
screen shot 2017-03-20 at 8 33 11 am
screen shot 2017-03-20 at 8 28 54 am

### CODE REVIEW

**Comment by willbkeller** [comment]
Great!

**Comment by willbkeller** [comment]
Just adding this in again with all the methods so you can double check and make sure you guys got them all.
suspension component diagram - page 1-2

**Comment by Wolfencode3000** [comment]
updated EconomySuspension test and stockspringtest

**Comment by willbkeller** [comment]
This all looks Great Marco! I ran your test and you have everything we need so I'm gonna merge it in!

**Comment by anthonykulis** [comment]
Im sorry, I cannot tell what was his task in here? I needed a slice of the full picture. I will look through commit ownership, but next round @willbkeller, I am holding you account

**Pull request merged**
