### PR TITLE
Template Final

### PR DESCRIPTION
**Pull request by NickAnson**

### CODE REVIEW

**Comment by willbkeller** [comment]
Hey Nick, sorry I'm just now getting to this, I've been traveling and then internet has been down. So what is going on here? you didn't have a description and i couldn't figure out what you are doing? thank you

**Comment by willbkeller** [comment]
Oh wait, did you just change up the directories? So now its how Anthony wants it?

**Comment by NickAnson** [comment]
Yah that how anthony wanted it pretty sure just made directories for each person to work in and a test file in each one so it would upload the files in the first place @willbkeller

**Comment by willbkeller** [comment]
Ok great! I'll merge it in @NickAnson

**Pull request merged**
